### ISSUE TITLE
this language is hard

### ISSUE THREAD

**Issue by ghost** [Creeperface01/BouncyBlocks#1]
dud..

**Comment by Creeperface01** [comment]
No it's easier!

**Comment by ghost** [comment]
not really

**Comment by sero583** [comment]
@Creeperface01 @NycuRO Its a weird one. ``fun`` instead of ``void``? But a thing what I like is, is ``var`` - like you don't need to create thousands of variables you can do it like you do in PHP simply one variable for any object, ``int, boolean, double`` and and and.

**Comment by Creeperface01** [comment]
@sero583 also you dont have to cast after instanceof

**Comment by Creeperface01** [comment]
And var is not like in PHP, kotlin just usually set variable type automatically, So if you create variable of type int you cant set for example String to it.

**Comment by sero583** [comment]
@Creeperface01 Well but it still reduces the amount of what you have to write, but I think Java is just fine and has more performance (?)

**Comment by sero583** [comment]
Well no this ain't true, because Java will be converted into bytecode and this too.

**Comment by Creeperface01** [comment]
Kotlin has the same performance. the most of changes Are only to make writing easier and faster for you.
